-- MySQL Script generated by MySQL Workbench
-- 08/17/17 14:09:55
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema mp3db
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `mp3db` ;

-- -----------------------------------------------------
-- Schema mp3db
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mp3db` DEFAULT CHARACTER SET utf8 ;
USE `mp3db` ;

-- -----------------------------------------------------
-- Table `mp3db`.`users`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mp3db`.`users` ;

CREATE TABLE IF NOT EXISTS `mp3db`.`users` (
  `userId` INT(11) NOT NULL AUTO_INCREMENT,
  `username` VARCHAR(255) NOT NULL,
  `password` VARCHAR(255) NOT NULL,
  `description` VARCHAR(255) NULL DEFAULT NULL,
  PRIMARY KEY (`userId`))
ENGINE = InnoDB
AUTO_INCREMENT = 1
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `mp3db`.`photos`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mp3db`.`photos` ;

CREATE TABLE IF NOT EXISTS `mp3db`.`photos` (
  `photoId` INT(11) NOT NULL AUTO_INCREMENT,
  `title` VARCHAR(255) NOT NULL,
  `description` VARCHAR(255) NULL DEFAULT NULL,
  `filepath` VARCHAR(255) NOT NULL,
  `privacy` VARCHAR(255) NOT NULL,
  `userid` INT(11) NOT NULL,
  PRIMARY KEY (`photoId`),
  CONSTRAINT `FKjy2sswrdt3w4t8ffuqwl26e0h`
    FOREIGN KEY (`userid`)
    REFERENCES `mp3db`.`users` (`userId`),
  CONSTRAINT `p_userId`
    FOREIGN KEY (`userid`)
    REFERENCES `mp3db`.`users` (`userId`))
ENGINE = InnoDB
AUTO_INCREMENT = 1
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `mp3db`.`alloweduser`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mp3db`.`alloweduser` ;

CREATE TABLE IF NOT EXISTS `mp3db`.`alloweduser` (
  `userId` INT(11) NOT NULL,
  `photoId` INT(11) NOT NULL,
  CONSTRAINT `FK67dov3nrhx924jxln2qn7wc8w`
    FOREIGN KEY (`userId`)
    REFERENCES `mp3db`.`users` (`userId`),
  CONSTRAINT `FKbmsgheoumv5olxqasnrg3u8m5`
    FOREIGN KEY (`photoId`)
    REFERENCES `mp3db`.`photos` (`photoId`),
  CONSTRAINT `au_photoid`
    FOREIGN KEY (`photoId`)
    REFERENCES `mp3db`.`photos` (`photoId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `au_userid`
    FOREIGN KEY (`userId`)
    REFERENCES `mp3db`.`users` (`userId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `mp3db`.`tags`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mp3db`.`tags` ;

CREATE TABLE IF NOT EXISTS `mp3db`.`tags` (
  `tagId` INT(11) NOT NULL AUTO_INCREMENT,
  `tagname` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`tagId`))
ENGINE = InnoDB
AUTO_INCREMENT = 1
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `mp3db`.`phototag`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mp3db`.`phototag` ;

CREATE TABLE IF NOT EXISTS `mp3db`.`phototag` (
  `photoId` INT(11) NOT NULL,
  `tagId` INT(11) NOT NULL,
  CONSTRAINT `FKjlpfxam6w4ij4jpqjyqscug6s`
    FOREIGN KEY (`photoId`)
    REFERENCES `mp3db`.`photos` (`photoId`),
  CONSTRAINT `FKnx8isfp0nenn7kt9rq74sgse9`
    FOREIGN KEY (`tagId`)
    REFERENCES `mp3db`.`tags` (`tagId`),
  CONSTRAINT `pt_photoid`
    FOREIGN KEY (`photoId`)
    REFERENCES `mp3db`.`photos` (`photoId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `pt_tagid`
    FOREIGN KEY (`tagId`)
    REFERENCES `mp3db`.`tags` (`tagId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
